---
- type: "Global"
  settings:
  - setting: "console_log_folder"
    description: "Console log file path"
    type: "folderPath"
  - setting: "debug_mode"
    description: "Debug mode"
    type: "boolean"
  - setting: "log.max_file_size_mb"
    description: "Maximum log file size (MB)"
    type: "String"
  - setting: "log_folder"
    description: "Log folder path"
    type: "folderPath"
  - setting: "log_folder_extractors"
    description: "Extractors log download path"
    type: "folderPath"
  - setting: "log_folder_extractors_ask_before_load"
    description: "Ask for a path before loading"
    type: "boolean"
  - setting: "log_folder_extractors_cassandra"
    description: "Cassandra extractor log path"
    type: "folderPath"
  - setting: "message_level.CLONE_DATACENTER"
    description: "Clone datacenter"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.COMPARE_SCHEMA"
    description: "Compare schema"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.CONTROLLER"
    description: "Controller"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.GENERAL"
    description: "General"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.INTERPRETATOR"
    description: "Application Analyzer"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.LOADER"
    description: "Loader"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.PARSER"
    description: "Parser"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.PRINTER"
    description: "Printer"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.RESOLVER"
    description: "Resolver"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.TELEMETRY"
    description: "Telemetry"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.TRANSFORMER"
    description: "Converter"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.TYPEMAPPING"
    description: "Type mapping"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.UI"
    description: "User interface"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "log.max_files_count"
    description: "Maximum log files count"
    type: "String"
  - setting: "parser.cleanup_mode"
    description: "Performance and memory management policy"
    type: "String"
    value:
    - "NEVER"
    - "AFTER_PARSING"
    - "ON_LOW_MEMORY"
  - setting: "open_file_after_action"
    description: "Auto show reports when saving"
    type: "boolean"
  - setting: "reporting.mode"
    description: "Action items occurrences"
  - setting: "showed-files-count"
    description: "SQL script analyzed files"
    type: "String"
  - setting: "show-all-files"
    description: "List all analyzwd files"
    type: "boolean"
  - setting: "mssql_auth_file"
    description: "SQL Server Windows Authentication library"
    type: "filePath"
  - setting: "DEFAULT_PROFILE_GENERAL"
    description: "Default profile"
    type: "String"
  - setting: "store_password"
    description: "Store connection passwords in project"
    type: "boolean"
  - setting: "key_user_certificate"
    description: "Show Extension Pack version alert"
    type: "boolean"
  - setting: "show_hide_schema_alert"
    description: "Show Hide schema alert"
    type: "boolean"
  - setting: "db2luw_driver_file"
    description: "DB2 LUW driver path"
    type: "filePath"
  - setting: "greenplum_driver_file"
    description: "Greenplum driver path"
    type: "filePath"
  - setting: "maria_driver_file"
    description: "MariaDB driver path"
    type: "filePath"
  - setting: "mssql_driver_file"
    description: "Microsoft SQL Server driver path"
    type: "filePath"
  - setting: "mysql_driver_file"
    description: "MySQL driver path"
    type: "filePath"
  - setting: "netezza_driver_file"
    description: "Netezza driver path"
    type: "filePath"
  - setting: "oracle_driver_file"
    description: "Oracle driver path"
    type: "filePath"
  - setting: "postgresql_driver_file"
    description: "PostgreSQL driver path"
    type: "filePath"
  - setting: "redshift_driver_file"
    description: "Amazon Redshift driver path"
    type: "filePath"
  - setting: "snowflake_driver_file"
    description: "Snowflake driver path"
    type: "filePath"
  - setting: "sybase_ase_driver_file"
    description: "SAP ASE (Sybase ASE) driver path"
    type: "filePath"
  - setting: "teradata_driver_files"
    description: "Teradata driver path"
    type: "filePath"
  - setting: "vertica_driver_file"
    description: "Vertica driver path"
    type: "filePath"
- type: "Project"
- type: "Default"
