---
- type: "Global"
  settings:
  - setting: "console_log_folder"
    description: "Console log file path"
    type: "folderPath"
  - setting: "debug_mode"
    description: "Debug mode"
    type: "boolean"
  - setting: "log.max_file_size_mb"
    description: "Maximum log file size (MB)"
    type: "String"
  - setting: "log_folder"
    description: "Log folder path"
    type: "folderPath"
  - setting: "log_folder_extractors"
    description: "Extractors log download path"
    type: "folderPath"
  - setting: "log_folder_extractors_ask_before_load"
    description: "Ask for a path before loading"
    type: "boolean"
  - setting: "log_folder_extractors_cassandra"
    description: "Cassandra extractor log path"
    type: "folderPath"
  - setting: "message_level.CLONE_DATACENTER"
    description: "Clone datacenter"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.COMPARE_SCHEMA"
    description: "Compare schema"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.CONTROLLER"
    description: "Controller"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.GENERAL"
    description: "General"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.INTERPRETATOR"
    description: "Application Analyzer"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.LOADER"
    description: "Loader"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.PARSER"
    description: "Parser"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.PRINTER"
    description: "Printer"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.RESOLVER"
    description: "Resolver"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.TELEMETRY"
    description: "Telemetry"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.TRANSFORMER"
    description: "Converter"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.TYPEMAPPING"
    description: "Type mapping"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "message_level.UI"
    description: "User interface"
    type: "String"
    value:
    - "INFO"
    - "TRACE"
    - "DEBUG"
    - "WARNING"
    - "ERROR"
    - "CRITICAL"
    - "MANDATORY"
  - setting: "log.max_files_count"
    description: "Maximum log files count"
    type: "String"
  - setting: "parser.cleanup_mode"
    description: "Performance and memory management policy"
    type: "String"
    value:
    - "NEVER"
    - "AFTER_PARSING"
    - "ON_LOW_MEMORY"
  - setting: "open_file_after_action"
    description: "Auto show reports when saving"
    type: "boolean"
  - setting: "reporting.mode"
    description: "Action items occurrences"
  - setting: "showed-files-count"
    description: "SQL script analyzed files"
    type: "String"
  - setting: "show-all-files"
    description: "List all analyzwd files"
    type: "boolean"
  - setting: "mssql_auth_file"
    description: "SQL Server Windows Authentication library"
    type: "filePath"
  - setting: "DEFAULT_PROFILE_GENERAL"
    description: "Default profile"
    type: "String"
  - setting: "store_password"
    description: "Store connection passwords in project"
    type: "boolean"
  - setting: "key_user_certificate"
    description: "Show Extension Pack version alert"
    type: "boolean"
  - setting: "show_hide_schema_alert"
    description: "Show Hide schema alert"
    type: "boolean"
  - setting: "db2luw_driver_file"
    description: "DB2 LUW driver path"
    type: "filePath"
  - setting: "greenplum_driver_file"
    description: "Greenplum driver path"
    type: "filePath"
  - setting: "maria_driver_file"
    description: "MariaDB driver path"
    type: "filePath"
  - setting: "mssql_driver_file"
    description: "Microsoft SQL Server driver path"
    type: "filePath"
  - setting: "mysql_driver_file"
    description: "MySQL driver path"
    type: "filePath"
  - setting: "netezza_driver_file"
    description: "Netezza driver path"
    type: "filePath"
  - setting: "oracle_driver_file"
    description: "Oracle driver path"
    type: "filePath"
  - setting: "postgresql_driver_file"
    description: "PostgreSQL driver path"
    type: "filePath"
  - setting: "redshift_driver_file"
    description: "Amazon Redshift driver path"
    type: "filePath"
  - setting: "snowflake_driver_file"
    description: "Snowflake driver path"
    type: "filePath"
  - setting: "sybase_ase_driver_file"
    description: "SAP ASE (Sybase ASE) driver path"
    type: "filePath"
  - setting: "teradata_driver_files"
    description: "Teradata driver path"
    type: "filePath"
  - setting: "vertica_driver_file"
    description: "Vertica driver path"
    type: "filePath"
- type: "Project"
  settings:
  - setting: "show_severity_level_in_sql"
    description: "How detailed should comments be in the converted SQL?"
    type: "String"
    value:
    - "CRITICAL"
    - "MEDIUM"
    - "LOW"
  - setting: "use_compression_encoding_zstd"
    description: "Use compression encoding ZSTD"
    type: "boolean"
  - setting: "use_compression_encoding_zstd_for_key_fields"
    description: "Use compression encoding ZSTD for KEY fields"
    type: "boolean"
  - setting: "skewed_max_value"
    description: "Skewed threshold value, %"
    type: "String"
  - setting: "sortkey_columns_limit"
    description: "Sort key columns limit"
    type: "String"
  - setting: "stat.query.history.top"
    description: "TopN query from QUERIES_HISTORY table"
    type: "String"
  - setting: "strategy"
    description: "Optimization strategies"
    type: "String"
    value:
    - "strategy_1"
    - "strategy_2"
    - "strategy_3"
  - setting: "save.sql.mode"
    description: "SQL script"
    type: "String"
    value:
    - "IN_ONE_FILE"
    - "N_ONE_FOLDER"
  - setting: "to_char_function_oracle"
    description: "Function TO_CHAR() does not use Oracle specific formatting strings"
    type: "boolean"
  - setting: "generate_row_id"
    description: "Generate row ID?"
    type: "String"
    value: 
    - "FALE"
    - "TRUE"
    - "GENERATE_AS_CHARACTER_DOMAIN_TYPE"
  - setting: "mysql_server_case_sensitivity"
    description: "Target Case Sensitivity"
    type: "String"
    value:
    - "CASE_SENSITIVE"
    - "CASE_INSENSITIVE"
  - setting: "materialized_view_convert"
    description: "Materialized View conversion as"
    type: "String"
    value:
    - "TABLE"
    - "MATERIALIZED_VIEW"
  - setting: "package_variables"
    description: "Package variables logic implementation"
    type: "String"
    value:
    - "PLV8_GLOBAL_OBJECTS"
    - "SESSION_VARIABLES"
  - setting: "to_char_function_oracle"
    description: "Function TO_CHAR() does not use Oracle specific formatting strings"
    type: "boolean"
  - setting: "to_date_function_oracle"
    description: "Function TO_DATE() does not use Oracle specific formatting strings"
    type: "boolean"
  - setting: "to_number"
    description: "Function TO_NUMBER() does not use Oracle specific formatting settings"
    type: "boolean"
  - setting: "to_time_zone"
    description: "Time zone on the client side matches the time zone on server"
    type: "boolean"
  - setting: "to_date_function_oracle"
    description: "Function TO_DATE() does not use Oracle specific formatting strings"
    type: "boolean"
  - setting: "to_number"
    description: "Function TO_NUMBER() does not use Oracle specific formatting settings"
    type: "boolean"
  - setting: "to_time_zone"
    description: "Time zone on the client side matches the time zone on server"
    type: "boolean"
  - setting: "alert_sequence_restart"
    description: "Populate converted sequences with the last value generated on the source side"
    type: "boolean"
  - setting: "convert_number_to_bigint"
    description: "Convert NUMBER primary / foreign key columns to BIGINT ones."
    type: "boolean"
  - setting: "ignore_disabled_triggers_constraints"
    description: "Ignore disabled triggers and constraints"
    type: "boolean"
  - setting: "convert_procedures_to_function"
    description: "Convert procedures to functions"
    type: "boolean"
  - setting: "bitand_builtin_function_oracle"
    description: "Built-in Function BITAND"
    type: "boolean"
  - setting: "cosh_builtin_function_oracle"
    description: "Built-in Function COSH"
    type: "boolean"
  - setting: "sinh_builtin_function_oracle"
    description: "Built-in Function SINH"
    type: "boolean"
  - setting: "add_months_builtin_function_oracle"
    description: "Built-in Function ADD_MONTHS"
    type: "boolean"
  - setting: "dbms_assert_builtin_function_oracle"
    description: "Built-in Package DBMS_ASSERT"
    type: "boolean"
  - setting: "dbms_output_builtin_function_oracle"
    description: "Built-in Package DBMS_OUTPUT"
    type: "boolean"
  - setting: "dbms_random_builtin_function_oracle"
    description: "Built-in Package DBMS_RANDOM"
    type: "boolean"
  - setting: "dbtimezone_builtin_function_oracle"
    description: "Built-in Function DBTIMEZONE"
    type: "boolean"
  - setting: "decode_builtin_function_oracle"
    description: "Built-in Function DECODE"
    type: "boolean"
  - setting: "dump_builtin_function_oracle"
    description: "Built-in Function DUMP"
    type: "boolean"
  - setting: "instr_builtin_function_oracle"
    description: "Built-in Function INSTR"
    type: "boolean"
  - setting: "instrb_builtin_function_oracle"
    description: "Built-in Function INSTRB"
    type: "boolean"
  - setting: "last_day_builtin_function_oracle"
    description: "Built-in Function LAST_DAY"
    type: "boolean"
  - setting: "length_builtin_function_oracle"
    description: "Built-in Function LENGTH"
    type: "boolean"
  - setting: "lengthb_builtin_function_oracle"
    description: "Built-in Function LENGTHB"
    type: "boolean"
  - setting: "listagg_builtin_function_oracle"
    description: "Built-in Function LISTAGG"
    type: "boolean"
  - setting: "lnnvl_builtin_function_oracle"
    description: "Built-in Function LNNVL"
    type: "boolean"
  - setting: "lpad_builtin_function_oracle"
    description: "Built-in Function LPAD"
    type: "boolean"
  - setting: "ltrim_builtin_function_oracle"
    description: "Built-in Function LTRIM"
    type: "boolean"
  - setting: "median_builtin_function_oracle"
    description: "Built-in Function MEDIAN"
    type: "boolean"
  - setting: "months_between_builtin_function_oracle"
    description: "Built-in Function MONTHS_BETWEEN"
    type: "boolean"
  - setting: "nanvl_builtin_function_oracle"
    description: "Built-in Function NANVL"
    type: "boolean"
  - setting: "next_day_builtin_function_oracle"
    description: "Built-in Function NEXT_DAY"
    type: "boolean"
  - setting: "nlssort_builtin_function_oracle"
    description: "Built-in Function NLSSORT"
    type: "boolean"
  - setting: "nvl2_builtin_function_oracle"
    description: "Built-in Function NVL2"
    type: "boolean"
  - setting: "nvl_builtin_function_oracle"
    description: "Built-in Function NVL"
    type: "boolean"
  - setting: "round_date_fmt_builtin_function_oracle"
    description: "Built-in Function ROUND(date [, fmt ])"
    type: "boolean"
  - setting: "round_number_builtin_function_oracle"
    description: "Built-in Function ROUND(number)"
    type: "boolean"
  - setting: "rpad_builtin_function_oracle"
    description: "Built-in Function RPAD"
    type: "boolean"
  - setting: "rtrim_builtin_function_oracle"
    description: "Built-in Function RTRIM"
    type: "boolean"
  - setting: "sessiontimezone_builtin_function_oracle"
    description: "Built-in Function SESSIONTIMEZONE"
    type: "boolean"
  - setting: "substr_builtin_function_oracle"
    description: "Built-in Function SUBSTR"
    type: "boolean"
  - setting: "substrb_builtin_function_oracle"
    description: "Built-in Function SUBSTRB"
    type: "boolean"
  - setting: "sysdate_builtin_function_oracle"
    description: "Built-in Function SYSDATE"
    type: "boolean"
  - setting: "tanh_builtin_function_oracle"
    description: "Built-in Function TANH"
    type: "boolean"
  - setting: "to_char_datetime_builtin_function_oracle"
    description: "Built-in Function TO_CHAR(datetime)"
    type: "boolean"
  - setting: "to_char_number_builtin_function_oracle"
    description: "Built-in Function TO_CHAR(number)"
    type: "boolean"
  - setting: "to_date_builtin_function_oracle"
    description: "Built-in Function TO_DATE"
    type: "boolean"
  - setting: "to_multi_byte_builtin_function_oracle"
    description: "Built-in Function TO_MULTI_BYTE"
    type: "boolean"
  - setting: "to_number_builtin_function_oracle"
    description: "Built-in Function TO_NUMBER"
    type: "boolean"
  - setting: "to_single_byte_builtin_function_oracle"
    description: "Built-in Function TO_SINGLE_BYTE"
    type: "boolean"
  - setting: "trunc_date_builtin_function_oracle"
    description: "Built-in Function TRUNC(date)"
    type: "boolean"
  - setting: "trunc_number_builtin_function_oracle"
    description: "Built-in Function TRUNC(number)"
    type: "boolean"
  - setting: "ext_pack_spatial"
    description: "Source database uses Oracle spatial"
    type: "String"
    value: 
    - "NO"
    - "YES"
  - setting: "use_dblinks_or_transactions"
    description: "Source database uses Database Links or Autonomous Transactions"
    type: "String"
    value: 
    - "NO"
    - "YES"
  - setting: "use_custom_extensions"
    description: "Use custom SQL script file extensions"
    type: "boolean"
  - setting: "extensions_list"
    description: "Enter new file extension"
    type: "String"
- type: "Default"
  settings:
  - setting: "olap_extractor_version"
    description: "AWS SCT Extractor version"
    type: "String"
    value:
    - "VERSION_1"
    - "VERSION_2"
  - setting: "storage.default_project_path"
    description: "Default project file path"
    type: "folderPath"
    